# -*- coding: utf-8 -*-
"""Assignment_day_2_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OS4d4BFAod5qji3JcucElnjavRNt4dpe
"""

x=[1,2,3,6,5,8,6,3,9,5,6,]
list(filter(lambda a: a != 6, x))